version: 'v1'
namespace: sap.ariba.ariba_sourcing
description: SAP ARIBA SOURCING 2
specVersion: 'v1'
authType: IAS
provisioningConfigs:
  - type: ASSISTANT_SETUP
    config:
      systemMetadata:
        - name: name
          source: ucl
          required: true
        - name: type
          source: application
          required: false
  - type: CONNECTIVITY_SETUP
    config:
      inboundCommunication:
        destinations:
          - name: SAMPLE
            authentication: oauth2mtls
            url: https://sample.url
            properties:
              - name: authentication
                value: oauth2mtls
              - name: clientId
                value: $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.clientId
              - name: correlationIds
                value: $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.correlationIds
