version: 'v1.0'
namespace: sap.ariba.ariba_sourcing
description: SAP ARIBA SOURCING
spec_version: 'v1'
auth_type: IAS
provisioning_configs:
  - type: ASSISTANT_SETUP
    config:
      system_metadata:
        - name: name
          source: ucl
          required: true
        - name: type
          source: application
          required: false
  - type: CONNECTIVITY_SETUP
    config:
      inbound_communication:
        destinations:
          - name: SAMPLE
            authentication: oauth2mtls
            url: https://sample.url
            properties:
              - name: authentication
                value: oauth2mtls
              - name: clientId
                value: $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.clientId
              - name: correlationIds
                value: $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.correlationIds
            additionalProperties:
              - name: URL.query.realmid
                value: $.assignedTenant.configuration.additionalProperties.aribaProperties[?(@.name == 'URL.queries.realmid')].value
              - name: URL.header.apikey
                value: $.assignedTenant.configuration.additionalProperties.aribaProperties[?(@.name == 'URL.queries.apikey')].value
