version: 1.0
schemaVersion: 0.0.1
namespace: sap.ariba.ariba_sourcing
description: SAP ARIBA SOURCING
authType: ias
provisioningConfigs:
  - type: setUpAssistant
    config:
      system_context:
        uclProvided:
          - name: uclSystemTenantId
            value: $.assignedTenant.uclSystemTenantId
            required: true
        lobProvided:
          - name: tokenServiceUrl
            value: >-
              $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.tokenServiceUrl
            required: false
  - type: setUpConnectivity
    config:
      credentials:
        inboundCommunication:
          oauth2mtls:
            clientId: >-
              $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.clientId
            correlationIds:
              - >-
                $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.correlationIds
