version: '1.0'
namespace: sap.ariba.ariba_sourcing
description: SAP ARIBA SOURCING
schemaVersion: 0.0.1
authType: ias
provisioningConfigs:
  - type: SetUpAssistant
    config:
      system_metadata:
        fields:
          - name: name
            value: $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.clientId
            source: ucl
            required: true
          - name: type
            value: $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.clientId
            source: lob
            required: false
  - type: SetUpConnectivity
    config:
      inbound_communication:
        destinations:
          - properties:
              - key: clientId
                value: $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.clientId
              - key: correlationIds
                value: $.assignedTenant.configuration.credentials.outboundCommunication.oauth2mtls.correlationIds
